oauth2:
  config:
    existingSecret: "oauth2-proxy-secret"
    configFile: |-
      provider = "keycloak-oidc"
      redirect_url = "https://{{ .Release.Name }}.skynex.cyberun.cloud/oauth2/callback"
      oidc_issuer_url = "https://identity.cyberun.cloud/realms/cyberun"
      upstreams = [ "http://{{ .Release.Name }}-comfyui:8188" ]
      email_domains = [ "*" ]
      skip_provider_button = false
      insecure_oidc_allow_unverified_email = true
  ingress:
    enabled: true
    className: cilium
    pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
    hosts:
      - "{{ .Release.Name }}.skynex.cyberun.cloud"
    tls:
      - secretName: "{{ .Release.Name }}-skynex-cyberun-cloud-tls"
        hosts:
          - "{{ .Release.Name }}.skynex.cyberun.cloud"
comfyui:
  image:
    tag: "cu128-slim"
  gpus:
    - "NVIDIA-H200-14C"
