apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  secretName: "{{ include "comfyui.domain" . }}-tls"
  dnsNames:
    - "{{ include "comfyui.domain" . }}"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
