resources:
  limits:
    cpu: "4"
    memory: "16Gi"
    nvidia.com/gpu: 1
  requests:
    cpu: "2"
    memory: "8Gi"
    nvidia.com/gpu: 1

persistence:
  volumes:
    comfyui-models:
      mountPath: /root/ComfyUI/models
    comfyui-outputs:
      mountPath: /root/ComfyUI/output
    comfyui-inputs:
      mountPath: /root/ComfyUI/input
    comfyui-workflows:
      mountPath: /root/ComfyUI/user/default/workflows

affinity: {}
gpus: []
