resources:
  limits:
    cpu: "4"
    memory: "16Gi"
    nvidia.com/gpu: 1
  requests:
    cpu: "2"
    memory: "8Gi"
    nvidia.com/gpu: 1

persistence:
  volumes:
    shared-models:
      mountPath: /root/ComfyUI/models
    shared-outputs:
      mountPath: /root/ComfyUI/output
    shared-inputs:
      mountPath: /root/ComfyUI/input
    shared-workflows:
      mountPath: /root/ComfyUI/user/default/workflows

affinity: {}
gpus: []

securityContext:
  fsGroup: 0
  seccompProfile:
    type: RuntimeDefault
