apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "comfyui.fullname" . }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.domain }}`)
      kind: Rule
      middlewares:
        - name: oauth2-auth
      services:
        - name: {{ include "comfyui.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    secretName: "{{ .Values.domain }}-tls"
