apiVersion: v1
kind: Service
metadata:
  name: {{ include "comfyui.fullname" . }}
  labels:
    {{- include "comfyui.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8188
      protocol: TCP
      name: http
  selector:
    {{- include "comfyui.selectorLabels" . | nindent 4 }}
