apiVersion: v2
name: gwork
version: 0.1.0
dependencies:
  - name: oauth2-proxy
    version: 10.0.0
    repository: https://oauth2-proxy.github.io/manifests/
    alias: oauth2
  - name: comfyui
    version: 0.1.0
    repository: file://../../charts/comfyui
    alias: comfyui
